/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddSchedule: typeof import('./src/components/AddSchedule.vue')['default']
    DailyCard: typeof import('./src/components/DailyCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    PersonPage: typeof import('./src/components/PersonPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCard: typeof import('./src/components/ScheduleCard.vue')['default']
  }
}
